### ISSUE TITLE
Interpreter: --ignore-errors option

### ISSUE THREAD

**Issue by bellrise** [xyLotus/astro#28]
The `--omit-errors` option would change the functionality of errors to not stop the program, just print them and continue.

**Comment by xyLotus** [comment]
I will try to add it, but can we call it "ignore-errors", or do you want "omit-errors", your decision.

**Comment by bellrise** [comment]
`--ignore-errors` sounds better and is more understandable.

**Comment by xyLotus** [comment]
Alright, as of V0.1.0 the "--ignoreErrors" argument got added. It, obviously got added as a optional CMDL argument ("-o").
