### ISSUE TITLE
Parser formatting suddenly changed, case: Array Type

### ISSUE THREAD

**Issue by xyLotus** [xyLotus/astro#30]
Usually the parser parses the assignment of a variable with the kw (in the current statement dict) 'params', but when a array assignment gets parsed the parser switches from keyword 'params' to 'data', thus making it more complicated to assign statement values in the interpeter backend.

**Comment by bellrise** [comment]
Fixed as of `asp3 3.5.0`, see the bottom of [this](https://github.com/xyLotus/astro/blob/main/asp/README.md) for an exact explation how to use this.
